name: BetterKeepInventory
version: '${version}'
main: biz.mcplay.betterkeepinventory.BetterKeepInventory
api-version: 1.17
authors: [ snake, MCPlayNetwork ]
website: www.mcplay.biz
commands:
  bkireload:
    description: Reloads the plugin.
    permission: betterkeepinventory.reload

permissions:
  betterkeepinventory.reload:
    description: Allows you to use /bkireload.
    default: op
